### ISSUE TITLE
Cannot get csrftoken on login/signin page

### ISSUE THREAD

**Issue by tweetythe** [aniket-tyagi-ru/Memrise-Audio-Uploader#1]
Hello can you check this issue ? When I try to login, cookies are empty and not contain **csrftoken**.
I tried my best but couldn't solve it..

**csrftoken = session.cookies.get_dict()['csrftoken']
KeyError: 'csrftoken'**

**Comment by aniket-tyagi-ru** [comment]
> Hello can you check this issue ? When I try to login, cookies are empty and not contain **csrftoken**. I tried my best but couldn't solve it..
> 
> **csrftoken = session.cookies.get_dict()['csrftoken'] KeyError: 'csrftoken'**

Hey, I forgot to update the repository ;)

Try the new release. You will need to copy your Memrise cookie instead of the Username and Password. It stopped working through Username/Password and I didn't have time to figure it out so went with the shortcut.

Tested it just now on a single page and it should work.

Note that if a single database is too large (maybe 2000+ words, don't remember exactly), for some mysterious reason memrise will not update the audio fields for automatic uploads, even though the file appears to have been uploaded successfully, so try to split larger databases into smaller ones. This can also happen intermittently on smaller databases so you may need to run the script a couple of times or fill the gaps manually. I don't remember the details since I have long since moved to Anki, but don't be surprised if something like this happens. Haven't had the patience and motivation to figure it out.

**Comment by tweetythe** [comment]
Hi mate, thanks it works. :)
